from pathlib import Path

src=Path('src/wgpu_boolean_selected_paged_decode.rs')
s=src.read_text()
marker='''    #[must_use]\n    pub fn generation(&self) -> u64 {\n        self.generation\n    }\n'''
method=marker+'''\n    /// Revalidate frozen sparse descriptors against the current authoritative\n    /// numerical page table immediately before GPU submission.\n    pub fn validate_against(\n        &self,\n        table: &PagedKvTable,\n    ) -> Result<(), BooleanSelectedPagedDecodeError> {\n        let telemetry = table.telemetry()?;\n        let config = table.config();\n        let frozen_mapped_pages = self.full_live_tokens.div_ceil(self.page_size);\n\n        if self.generation != telemetry.generation {\n            return Err(BooleanSelectedPagedDecodeError::GenerationMismatch {\n                selection_generation: self.generation,\n                table_generation: telemetry.generation,\n            });\n        }\n        if self.full_live_tokens != telemetry.live_tokens\n            || frozen_mapped_pages != telemetry.mapped_pages\n            || self.page_size != config.page_size\n            || self.physical_pages != config.physical_pages\n        {\n            return Err(BooleanSelectedPagedDecodeError::SnapshotMismatch {\n                selection_live_tokens: self.full_live_tokens,\n                table_live_tokens: telemetry.live_tokens,\n                selection_mapped_pages: frozen_mapped_pages,\n                table_mapped_pages: telemetry.mapped_pages,\n            });\n        }\n\n        for entry in &self.entries {\n            let first_token = entry.logical_page.checked_mul(config.page_size).ok_or(\n                BooleanSelectedPagedDecodeError::IndexSpaceExceeded {\n                    elements: entry.logical_page,\n                },\n            )?;\n            let address = table.address(first_token).ok_or(\n                BooleanSelectedPagedDecodeError::MissingAuthoritativePage {\n                    logical_page: entry.logical_page,\n                },\n            )?;\n            if entry.physical_page != address.physical_page {\n                return Err(BooleanSelectedPagedDecodeError::PhysicalPageMismatch {\n                    logical_page: entry.logical_page,\n                    selected_physical_page: entry.physical_page,\n                    authoritative_physical_page: address.physical_page,\n                });\n            }\n            let remaining = telemetry.live_tokens.checked_sub(first_token).ok_or(\n                BooleanSelectedPagedDecodeError::IndexSpaceExceeded {\n                    elements: first_token,\n                },\n            )?;\n            let expected_live_tokens = remaining.min(config.page_size);\n            if entry.live_tokens != expected_live_tokens {\n                return Err(BooleanSelectedPagedDecodeError::LiveTokenMismatch {\n                    logical_page: entry.logical_page,\n                    selected_live_tokens: entry.live_tokens,\n                    authoritative_live_tokens: expected_live_tokens,\n                });\n            }\n        }\n        Ok(())\n    }\n'''
assert marker in s
s=s.replace(marker,method,1)
s=s.replace("    pub page_table: &'a BooleanSelectedPagedKvTable,\n    pub out_and_lse:","    pub page_table: &'a BooleanSelectedPagedKvTable,\n    /// Current numerical table, revalidated immediately before encoding.\n    pub authoritative_table: &'a PagedKvTable,\n    pub out_and_lse:",1)
s=s.replace('    ) -> Result<BooleanSelectedDecodeLayout, BooleanSelectedPagedDecodeError> {\n        if pass.page_table.entries.is_empty()','    ) -> Result<BooleanSelectedDecodeLayout, BooleanSelectedPagedDecodeError> {\n        pass.page_table.validate_against(pass.authoritative_table)?;\n        if pass.page_table.entries.is_empty()',1)
src.write_text(s)

test=Path('tests/bkv6_selected_paged_decode.rs')
t=test.read_text()
t=t.replace('    page_table: &BooleanSelectedPagedKvTable,\n    inputs: DeviceInputs','    page_table: &BooleanSelectedPagedKvTable,\n    authoritative_table: &PagedKvTable,\n    inputs: DeviceInputs',1)
t=t.replace('                page_table,\n                out_and_lse:','                page_table,\n                authoritative_table,\n                out_and_lse:',1)
t=t.replace('run_selected(&harness, &pipeline, &all_table, inputs, geometry)','run_selected(&harness, &pipeline, &all_table, &table, inputs, geometry)',1)
t=t.replace('run_selected(&harness, &pipeline, &sparse_table, inputs, geometry)','run_selected(&harness, &pipeline, &sparse_table, &table, inputs, geometry)',1)
anchor='''    let mut stale = sparse;\n    stale.generation += 1;\n    assert!(matches!(\n        BooleanSelectedPagedKvTable::from_selection(&stale, &table),\n        Err(BooleanSelectedPagedDecodeError::GenerationMismatch { .. })\n    ));\n}\n'''
replacement='''    let mut stale = sparse;\n    stale.generation += 1;\n    assert!(matches!(\n        BooleanSelectedPagedKvTable::from_selection(&stale, &table),\n        Err(BooleanSelectedPagedDecodeError::GenerationMismatch { .. })\n    ));\n\n    let mut changed_table = table;\n    changed_table.truncate(2).unwrap();\n    assert!(matches!(\n        selected.validate_against(&changed_table),\n        Err(BooleanSelectedPagedDecodeError::SnapshotMismatch { .. })\n    ));\n    changed_table.reset().unwrap();\n    assert!(matches!(\n        selected.validate_against(&changed_table),\n        Err(BooleanSelectedPagedDecodeError::GenerationMismatch { .. })\n    ));\n}\n'''
assert anchor in t
t=t.replace(anchor,replacement,1)
test.write_text(t)
