//! M13 additive attention-bias contract for rectangular projection-layout attention.
//!
//! This module extends the deterministic scalar oracle without changing any
//! qualified GPU kernel. Bias values are added to the scaled Q·K score before
//! the online-softmax update, so no score/probability matrix is materialized.

use super::{
    AsymmetricGroupedAttentionShape, AsymmetricRotaryEmbeddingConfig, FlatAttentionConfig,
    FlatAttentionError, FlatAttentionOutput,
};

/// Optional score bias for asymmetric projection-layout attention.
///
/// `Dense` uses logical layout `[batch, q_heads, query_len, kv_len]`.
/// `Alibi` accepts one slope per query head and computes
/// `slope[head] * (key_position - query_position)` from explicit absolute
/// position origins. FLAT deliberately does not prescribe how slopes are
/// generated by a model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum AttentionBias<'a> {
    None,
    Dense(&'a [f32]),
    Alibi {
        slopes: &'a [f32],
        query_position_offset: usize,
        kv_position_offset: usize,
    },
}

impl<'a> AttentionBias<'a> {
    fn validate(self, shape: AsymmetricGroupedAttentionShape) -> Result<(), FlatAttentionError> {
        match self {
            Self::None => Ok(()),
            Self::Dense(values) => {
                let expected = shape
                    .batch
                    .checked_mul(shape.q_heads)
                    .and_then(|n| n.checked_mul(shape.query_len))
                    .and_then(|n| n.checked_mul(shape.kv_len))
                    .ok_or(FlatAttentionError::ShapeOverflow)?;
                validate_bias_input("attention bias", values, expected)
            }
            Self::Alibi {
                slopes,
                query_position_offset,
                kv_position_offset,
            } => {
                validate_bias_input("ALiBi slopes", slopes, shape.q_heads)?;
                query_position_offset
                    .checked_add(shape.query_len.saturating_sub(1))
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                kv_position_offset
                    .checked_add(shape.kv_len.saturating_sub(1))
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                Ok(())
            }
        }
    }

    #[inline]
    fn score_bias(
        self,
        shape: AsymmetricGroupedAttentionShape,
        batch: usize,
        q_head: usize,
        query_pos: usize,
        key_pos: usize,
    ) -> Result<f32, FlatAttentionError> {
        match self {
            Self::None => Ok(0.0),
            Self::Dense(values) => {
                let index = batch
                    .checked_mul(shape.q_heads)
                    .and_then(|n| n.checked_add(q_head))
                    .and_then(|n| n.checked_mul(shape.query_len))
                    .and_then(|n| n.checked_add(query_pos))
                    .and_then(|n| n.checked_mul(shape.kv_len))
                    .and_then(|n| n.checked_add(key_pos))
                    .ok_or(FlatAttentionError::ShapeOverflow)?;
                Ok(values[index])
            }
            Self::Alibi {
                slopes,
                query_position_offset,
                kv_position_offset,
            } => {
                let query_position = query_position_offset
                    .checked_add(query_pos)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                let key_position = kv_position_offset
                    .checked_add(key_pos)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                let delta = key_position as f64 - query_position as f64;
                Ok(slopes[q_head] * delta as f32)
            }
        }
    }
}

fn validate_bias_input(
    name: &'static str,
    data: &[f32],
    expected: usize,
) -> Result<(), FlatAttentionError> {
    if data.len() != expected {
        return Err(FlatAttentionError::LengthMismatch {
            tensor: name,
            actual: data.len(),
            expected,
        });
    }
    if let Some(index) = data.iter().position(|value| !value.is_finite()) {
        return Err(FlatAttentionError::NonFiniteInput {
            tensor: name,
            index,
        });
    }
    Ok(())
}

#[inline]
fn projection_index(
    batch: usize,
    position: usize,
    head: usize,
    dim: usize,
    heads: usize,
    seq_len: usize,
    head_dim: usize,
) -> Result<usize, FlatAttentionError> {
    let width = heads
        .checked_mul(head_dim)
        .ok_or(FlatAttentionError::ShapeOverflow)?;
    batch
        .checked_mul(seq_len)
        .and_then(|row| row.checked_add(position))
        .and_then(|row| row.checked_mul(width))
        .and_then(|base| {
            head.checked_mul(head_dim)
                .and_then(|head_base| base.checked_add(head_base))
        })
        .and_then(|base| base.checked_add(dim))
        .ok_or(FlatAttentionError::ShapeOverflow)
}

#[inline]
fn rotated_pair(
    even: f32,
    odd: f32,
    pair: usize,
    head_dim: usize,
    position: usize,
    theta: f32,
) -> (f32, f32) {
    let exponent = -2.0 * pair as f32 / head_dim as f32;
    let frequency = theta.powf(exponent);
    let angle = position as f32 * frequency;
    let (sin, cos) = angle.sin_cos();
    (even * cos - odd * sin, even * sin + odd * cos)
}

/// Deterministic scalar oracle for M13 additive score bias.
///
/// Bias is applied after score scaling and before the online-softmax update.
/// The implementation remains streaming in K/V and never allocates a
/// `query_len * kv_len` score or probability matrix.
pub fn forward_reference_projection_grouped_rope_asymmetric_biased(
    q: &[f32],
    k: &[f32],
    v: &[f32],
    shape: AsymmetricGroupedAttentionShape,
    config: FlatAttentionConfig,
    rotary: AsymmetricRotaryEmbeddingConfig,
    bias: AttentionBias<'_>,
) -> Result<FlatAttentionOutput, FlatAttentionError> {
    shape.validate()?;
    rotary.validate(shape.head_dim, shape.query_len, shape.kv_len)?;
    bias.validate(shape)?;

    let q_len = shape.q_tensor_len()?;
    let kv_len = shape.kv_tensor_len()?;
    validate_bias_input("Q", q, q_len)?;
    validate_bias_input("K", k, kv_len)?;
    validate_bias_input("V", v, kv_len)?;
    let scale = config.resolved_scale(shape.head_dim)?;
    let group_size = shape.q_heads / shape.kv_heads;

    let mut output = vec![0.0f32; q_len];
    let mut lse = vec![0.0f32; shape.lse_len()?];

    for batch in 0..shape.batch {
        for q_head in 0..shape.q_heads {
            let kv_head = q_head / group_size;
            let lse_base = (batch * shape.q_heads + q_head) * shape.query_len;

            for query_pos in 0..shape.query_len {
                let causal_query_position = shape
                    .query_position_offset
                    .checked_add(query_pos)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                let query_rotary_position = rotary
                    .query_position_offset
                    .checked_add(query_pos)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                let mut running_max = f32::NEG_INFINITY;
                let mut running_sum = 0.0f32;

                for key_pos in 0..shape.kv_len {
                    if config.causal && key_pos > causal_query_position {
                        break;
                    }
                    let key_rotary_position = rotary
                        .kv_position_offset
                        .checked_add(key_pos)
                        .ok_or(FlatAttentionError::PositionOverflow)?;
                    let mut dot = 0.0f32;
                    for pair in 0..shape.head_dim / 2 {
                        let dim = 2 * pair;
                        let qe_idx = projection_index(
                            batch,
                            query_pos,
                            q_head,
                            dim,
                            shape.q_heads,
                            shape.query_len,
                            shape.head_dim,
                        )?;
                        let ke_idx = projection_index(
                            batch,
                            key_pos,
                            kv_head,
                            dim,
                            shape.kv_heads,
                            shape.kv_len,
                            shape.head_dim,
                        )?;
                        let (qe, qo) = rotated_pair(
                            q[qe_idx],
                            q[qe_idx + 1],
                            pair,
                            shape.head_dim,
                            query_rotary_position,
                            rotary.theta,
                        );
                        let (ke, ko) = rotated_pair(
                            k[ke_idx],
                            k[ke_idx + 1],
                            pair,
                            shape.head_dim,
                            key_rotary_position,
                            rotary.theta,
                        );
                        dot += qe * ke;
                        dot += qo * ko;
                    }

                    let score = dot * scale
                        + bias.score_bias(shape, batch, q_head, query_pos, key_pos)?;
                    let new_max = running_max.max(score);
                    let alpha = if running_max.is_infinite() {
                        0.0
                    } else {
                        (running_max - new_max).exp()
                    };
                    let probability_numerator = (score - new_max).exp();

                    for dim in 0..shape.head_dim {
                        let out_idx = projection_index(
                            batch,
                            query_pos,
                            q_head,
                            dim,
                            shape.q_heads,
                            shape.query_len,
                            shape.head_dim,
                        )?;
                        let v_idx = projection_index(
                            batch,
                            key_pos,
                            kv_head,
                            dim,
                            shape.kv_heads,
                            shape.kv_len,
                            shape.head_dim,
                        )?;
                        output[out_idx] =
                            output[out_idx] * alpha + probability_numerator * v[v_idx];
                    }
                    running_sum = running_sum * alpha + probability_numerator;
                    running_max = new_max;
                }

                let inv_sum = running_sum.recip();
                for dim in 0..shape.head_dim {
                    let out_idx = projection_index(
                        batch,
                        query_pos,
                        q_head,
                        dim,
                        shape.q_heads,
                        shape.query_len,
                        shape.head_dim,
                    )?;
                    output[out_idx] *= inv_sum;
                }
                lse[lse_base + query_pos] = running_max + running_sum.ln();
            }
        }
    }

    Ok(FlatAttentionOutput { output, lse })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::forward_reference_projection_grouped_rope_asymmetric;

    fn fixture(len: usize, phase: f32) -> Vec<f32> {
        (0..len)
            .map(|index| ((index as f32 * 0.071) + phase).sin() * 0.625)
            .collect()
    }

    fn shape() -> AsymmetricGroupedAttentionShape {
        AsymmetricGroupedAttentionShape {
            batch: 1,
            q_heads: 4,
            kv_heads: 2,
            query_len: 3,
            kv_len: 5,
            head_dim: 8,
            query_position_offset: 2,
        }
    }

    fn rotary() -> AsymmetricRotaryEmbeddingConfig {
        AsymmetricRotaryEmbeddingConfig {
            theta: 10_000.0,
            query_position_offset: 17,
            kv_position_offset: 13,
        }
    }

    #[test]
    fn no_bias_is_bitwise_identical_to_m11_oracle() {
        let shape = shape();
        let q = fixture(shape.q_tensor_len().unwrap(), 0.2);
        let k = fixture(shape.kv_tensor_len().unwrap(), 0.8);
        let v = fixture(shape.kv_tensor_len().unwrap(), 1.4);
        let config = FlatAttentionConfig {
            causal: false,
            softmax_scale: None,
        };
        let expected = forward_reference_projection_grouped_rope_asymmetric(
            &q,
            &k,
            &v,
            shape,
            config,
            rotary(),
        )
        .unwrap();
        let actual = forward_reference_projection_grouped_rope_asymmetric_biased(
            &q,
            &k,
            &v,
            shape,
            config,
            rotary(),
            AttentionBias::None,
        )
        .unwrap();
        assert_eq!(actual, expected);
    }

    #[test]
    fn dense_bias_changes_softmax_without_score_matrix() {
        let shape = AsymmetricGroupedAttentionShape {
            batch: 1,
            q_heads: 1,
            kv_heads: 1,
            query_len: 1,
            kv_len: 2,
            head_dim: 2,
            query_position_offset: 0,
        };
        let q = vec![0.0, 0.0];
        let k = vec![0.0, 0.0, 0.0, 0.0];
        let v = vec![1.0, 2.0, 3.0, 4.0];
        let bias = vec![0.0, 3.0f32.ln()];
        let output = forward_reference_projection_grouped_rope_asymmetric_biased(
            &q,
            &k,
            &v,
            shape,
            FlatAttentionConfig {
                causal: false,
                softmax_scale: None,
            },
            AsymmetricRotaryEmbeddingConfig {
                theta: 10_000.0,
                query_position_offset: 0,
                kv_position_offset: 0,
            },
            AttentionBias::Dense(&bias),
        )
        .unwrap();
        assert!((output.output[0] - 2.5).abs() <= 1.0e-6);
        assert!((output.output[1] - 3.5).abs() <= 1.0e-6);
        assert!((output.lse[0] - 4.0f32.ln()).abs() <= 1.0e-6);
    }

    #[test]
    fn alibi_matches_equivalent_dense_bias() {
        let shape = shape();
        let q = fixture(shape.q_tensor_len().unwrap(), 0.3);
        let k = fixture(shape.kv_tensor_len().unwrap(), 0.9);
        let v = fixture(shape.kv_tensor_len().unwrap(), 1.5);
        let slopes = [0.25, 0.5, 0.75, 1.0];
        let query_origin = 31usize;
        let kv_origin = 29usize;
        let mut dense = Vec::with_capacity(shape.batch * shape.q_heads * shape.query_len * shape.kv_len);
        for _batch in 0..shape.batch {
            for &slope in &slopes {
                for query_pos in 0..shape.query_len {
                    for key_pos in 0..shape.kv_len {
                        let delta = (kv_origin + key_pos) as f32 - (query_origin + query_pos) as f32;
                        dense.push(slope * delta);
                    }
                }
            }
        }
        let config = FlatAttentionConfig {
            causal: false,
            softmax_scale: None,
        };
        let dense_output = forward_reference_projection_grouped_rope_asymmetric_biased(
            &q,
            &k,
            &v,
            shape,
            config,
            rotary(),
            AttentionBias::Dense(&dense),
        )
        .unwrap();
        let alibi_output = forward_reference_projection_grouped_rope_asymmetric_biased(
            &q,
            &k,
            &v,
            shape,
            config,
            rotary(),
            AttentionBias::Alibi {
                slopes: &slopes,
                query_position_offset: query_origin,
                kv_position_offset: kv_origin,
            },
        )
        .unwrap();
        assert_eq!(alibi_output, dense_output);
    }

    #[test]
    fn malformed_biases_fail_explicitly() {
        let shape = shape();
        let q = fixture(shape.q_tensor_len().unwrap(), 0.2);
        let k = fixture(shape.kv_tensor_len().unwrap(), 0.8);
        let v = fixture(shape.kv_tensor_len().unwrap(), 1.4);
        let error = forward_reference_projection_grouped_rope_asymmetric_biased(
            &q,
            &k,
            &v,
            shape,
            FlatAttentionConfig::default(),
            rotary(),
            AttentionBias::Dense(&[0.0]),
        )
        .unwrap_err();
        assert!(matches!(error, FlatAttentionError::LengthMismatch { tensor: "attention bias", .. }));

        let slopes = [0.0, f32::NAN, 0.0, 0.0];
        let error = forward_reference_projection_grouped_rope_asymmetric_biased(
            &q,
            &k,
            &v,
            shape,
            FlatAttentionConfig::default(),
            rotary(),
            AttentionBias::Alibi {
                slopes: &slopes,
                query_position_offset: 0,
                kv_position_offset: 0,
            },
        )
        .unwrap_err();
        assert_eq!(
            error,
            FlatAttentionError::NonFiniteInput {
                tensor: "ALiBi slopes",
                index: 1,
            }
        );
    }
}
