//! M13 additive attention-bias contract for rectangular projection-layout attention.
//!
//! This module extends the deterministic scalar oracle without changing any
//! qualified GPU kernel. Bias values are added to the scaled Q·K score before
//! the online-softmax update, so no score/probability matrix is materialized.

use super::{
    AsymmetricGroupedAttentionShape, AsymmetricRotaryEmbeddingConfig, FlatAttentionConfig,
    FlatAttentionError, FlatAttentionOutput,
};

/// Optional score bias for asymmetric projection-layout attention.
///
/// `Dense` uses logical layout `[batch, q_heads, query_len, kv_len]`.
/// `Alibi` accepts one slope per query head and computes
/// `slope[head] * (key_position - query_position)` from explicit absolute
/// position origins. FLAT deliberately does not prescribe how slopes are
/// generated by a model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum AttentionBias<'a> {
    None,
    Dense(&'a [f32]),
    Alibi {
        slopes: &'a [f32],
        query_position_offset: usize,
        kv_position_offset: usize,
    },
}

impl<'a> AttentionBias<'a> {
    fn validate(self, shape: AsymmetricGroupedAttentionShape) -> Result<(), FlatAttentionError> {
        match self {
            Self::None => Ok(()),
            Self::Dense(values) => {
                let expected = shape
                    .batch
                    .checked_mul(shape.q_heads)
                    .and_then(|n| n.checked_mul(shape.query_len))
                    .and_then(|n| n.checked_mul(shape.kv_len))
                    .ok_or(FlatAttentionError::ShapeOverflow)?;
                validate_input("attention bias", values, expected)
            }
            Self::Alibi {
                slopes,
                query_position_offset,
                kv_position_offset,
            } => {
                validate_input("ALiBi slopes", slopes, shape.q_heads)?;
                query_position_offset
                    .checked_add(shape.query_len - 1)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                kv_position_offset
                    .checked_add(shape.kv_len - 1)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                Ok(())
            }
        }
    }

    #[inline]
    fn score(
        self,
        shape: AsymmetricGroupedAttentionShape,
        batch: usize,
        q_head: usize,
        query_pos: usize,
        key_pos: usize,
    ) -> Result<f32, FlatAttentionError> {
        match self {
            Self::None => Ok(0.0),
            Self::Dense(values) => {
                let index = batch
                    .checked_mul(shape.q_heads)
                    .and_then(|n| n.checked_add(q_head))
                    .and_then(|n| n.checked_mul(shape.query_len))
                    .and_then(|n| n.checked_add(query_pos))
                    .and_then(|n| n.checked_mul(shape.kv_len))
                    .and_then(|n| n.checked_add(key_pos))
                    .ok_or(FlatAttentionError::ShapeOverflow)?;
                Ok(values[index])
            }
            Self::Alibi {
                slopes,
                query_position_offset,
                kv_position_offset,
            } => {
                let query_position = query_position_offset
                    .checked_add(query_pos)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                let key_position = kv_position_offset
                    .checked_add(key_pos)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                let delta = key_position as f64 - query_position as f64;
                Ok(slopes[q_head] * delta as f32)
            }
        }
    }
}

fn validate_shape(shape: AsymmetricGroupedAttentionShape) -> Result<(), FlatAttentionError> {
    if shape.batch == 0
        || shape.q_heads == 0
        || shape.kv_heads == 0
        || shape.query_len == 0
        || shape.kv_len == 0
        || shape.head_dim == 0
    {
        return Err(FlatAttentionError::ZeroDimension);
    }
    if shape.q_heads % shape.kv_heads != 0 {
        return Err(FlatAttentionError::InvalidHeadGrouping {
            q_heads: shape.q_heads,
            kv_heads: shape.kv_heads,
        });
    }
    shape
        .query_position_offset
        .checked_add(shape.query_len - 1)
        .ok_or(FlatAttentionError::ShapeOverflow)?;
    shape.q_tensor_len()?;
    shape.kv_tensor_len()?;
    shape.lse_len()?;
    Ok(())
}

fn validate_input(
    name: &'static str,
    values: &[f32],
    expected: usize,
) -> Result<(), FlatAttentionError> {
    if values.len() != expected {
        return Err(FlatAttentionError::LengthMismatch {
            tensor: name,
            actual: values.len(),
            expected,
        });
    }
    if let Some(index) = values.iter().position(|value| !value.is_finite()) {
        return Err(FlatAttentionError::NonFiniteInput {
            tensor: name,
            index,
        });
    }
    Ok(())
}

#[inline]
fn projection_index(
    batch: usize,
    position: usize,
    head: usize,
    dim: usize,
    heads: usize,
    seq_len: usize,
    head_dim: usize,
) -> Result<usize, FlatAttentionError> {
    let width = heads
        .checked_mul(head_dim)
        .ok_or(FlatAttentionError::ShapeOverflow)?;
    batch
        .checked_mul(seq_len)
        .and_then(|row| row.checked_add(position))
        .and_then(|row| row.checked_mul(width))
        .and_then(|base| {
            head.checked_mul(head_dim)
                .and_then(|head_base| base.checked_add(head_base))
        })
        .and_then(|base| base.checked_add(dim))
        .ok_or(FlatAttentionError::ShapeOverflow)
}

#[inline]
fn rotated_pair(
    even: f32,
    odd: f32,
    pair: usize,
    head_dim: usize,
    position: usize,
    theta: f32,
) -> (f32, f32) {
    let exponent = -2.0 * pair as f32 / head_dim as f32;
    let frequency = theta.powf(exponent);
    let angle = position as f32 * frequency;
    let (sin, cos) = angle.sin_cos();
    (even * cos - odd * sin, even * sin + odd * cos)
}

/// Deterministic scalar oracle for M13 additive score bias.
///
/// Bias is applied after score scaling and before the online-softmax update.
/// The implementation remains streaming in K/V and never allocates a
/// `query_len * kv_len` score or probability matrix.
pub fn forward_reference_projection_grouped_rope_asymmetric_biased(
    q: &[f32],
    k: &[f32],
    v: &[f32],
    shape: AsymmetricGroupedAttentionShape,
    config: FlatAttentionConfig,
    rotary: AsymmetricRotaryEmbeddingConfig,
    bias: AttentionBias<'_>,
) -> Result<FlatAttentionOutput, FlatAttentionError> {
    validate_shape(shape)?;
    rotary.validate(shape.head_dim, shape.query_len, shape.kv_len)?;
    bias.validate(shape)?;

    let q_len = shape.q_tensor_len()?;
    let kv_len = shape.kv_tensor_len()?;
    validate_input("Q", q, q_len)?;
    validate_input("K", k, kv_len)?;
    validate_input("V", v, kv_len)?;
    let scale = config.resolved_scale(shape.head_dim)?;
    let group_size = shape.q_heads / shape.kv_heads;

    let mut output = vec![0.0f32; q_len];
    let mut lse = vec![0.0f32; shape.lse_len()?];

    for batch in 0..shape.batch {
        for q_head in 0..shape.q_heads {
            let kv_head = q_head / group_size;
            let lse_base = (batch * shape.q_heads + q_head) * shape.query_len;

            for query_pos in 0..shape.query_len {
                let causal_query_position = shape
                    .query_position_offset
                    .checked_add(query_pos)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                let query_rotary_position = rotary
                    .query_position_offset
                    .checked_add(query_pos)
                    .ok_or(FlatAttentionError::PositionOverflow)?;
                let mut running_max = f32::NEG_INFINITY;
                let mut running_sum = 0.0f32;

                for key_pos in 0..shape.kv_len {
                    if config.causal && key_pos > causal_query_position {
                        break;
                    }
                    let key_rotary_position = rotary
                        .kv_position_offset
                        .checked_add(key_pos)
                        .ok_or(FlatAttentionError::PositionOverflow)?;
                    let mut dot = 0.0f32;

                    for pair in 0..shape.head_dim / 2 {
                        let dim = 2 * pair;
                        let q_index = projection_index(
                            batch,
                            query_pos,
                            q_head,
                            dim,
                            shape.q_heads,
                            shape.query_len,
                            shape.head_dim,
                        )?;
                        let k_index = projection_index(
                            batch,
                            key_pos,
                            kv_head,
                            dim,
                            shape.kv_heads,
                            shape.kv_len,
                            shape.head_dim,
                        )?;
                        let (q_even, q_odd) = rotated_pair(
                            q[q_index],
                            q[q_index + 1],
                            pair,
                            shape.head_dim,
                            query_rotary_position,
                            rotary.theta,
                        );
                        let (k_even, k_odd) = rotated_pair(
                            k[k_index],
                            k[k_index + 1],
                            pair,
                            shape.head_dim,
                            key_rotary_position,
                            rotary.theta,
                        );
                        dot += q_even * k_even + q_odd * k_odd;
                    }

                    let score =
                        dot * scale + bias.score(shape, batch, q_head, query_pos, key_pos)?;
                    let new_max = running_max.max(score);
                    let alpha = if running_max.is_infinite() {
                        0.0
                    } else {
                        (running_max - new_max).exp()
                    };
                    let probability_numerator = (score - new_max).exp();

                    for dim in 0..shape.head_dim {
                        let output_index = projection_index(
                            batch,
                            query_pos,
                            q_head,
                            dim,
                            shape.q_heads,
                            shape.query_len,
                            shape.head_dim,
                        )?;
                        let value_index = projection_index(
                            batch,
                            key_pos,
                            kv_head,
                            dim,
                            shape.kv_heads,
                            shape.kv_len,
                            shape.head_dim,
                        )?;
                        output[output_index] =
                            output[output_index] * alpha + probability_numerator * v[value_index];
                    }
                    running_sum = running_sum * alpha + probability_numerator;
                    running_max = new_max;
                }

                let inverse_sum = running_sum.recip();
                for dim in 0..shape.head_dim {
                    let output_index = projection_index(
                        batch,
                        query_pos,
                        q_head,
                        dim,
                        shape.q_heads,
                        shape.query_len,
                        shape.head_dim,
                    )?;
                    output[output_index] *= inverse_sum;
                }
                lse[lse_base + query_pos] = running_max + running_sum.ln();
            }
        }
    }

    Ok(FlatAttentionOutput { output, lse })
}
